package model

import "gorm.io/gorm"

type EcomOrder struct {
	gorm.Model
	Id                     int     `json:"id"`
	Code                   string  `json:"code"`
	RefCode                string  `json:"ref_code"`
	OriginalOrderId        int     `json:"original_order_id"`
	ReturnOrderId          int     `json:"return_order_id"`
	CustomerId             int     `json:"customer_id"`
	SellerOrgId            int     `json:"seller_org_id"`
	SellerUserId           int     `json:"seller_user_id"`
	BuyerOrgId             int     `json:"buyer_org_id"`
	BuyerUserId            int     `json:"buyer_user_id"`
	TransId                string  `json:"trans_id"`
	TransDate              string  `json:"trans_date"`
	OrderDate              string  `json:"order_date"`
	Quantity               int     `json:"quantity"`
	TotalBasePrice         float64 `json:"total_base_price"`
	OrderAmount            float64 `json:"order_amount"`
	ShippingFee            int     `json:"shipping_fee"`
	TotalAmount            float64 `json:"total_amount"`
	DiscountAmount         int     `json:"discount_amount"`
	TransAmount            float64 `json:"trans_amount"`
	PaidAmount             float64 `json:"paid_amount"`
	PaymentChannel         string  `json:"payment_channel"`
	PaymentStatus          string  `json:"payment_status"`
	ShippingType           string  `json:"shipping_type"`
	VoucherCode            string  `json:"voucher_code"`
	VoucherValue           float64 `json:"voucher_value"`
	OrderType              float64 `json:"order_type"`
	PartnerDeliveryId      int     `json:"partner_delivery_id"`
	DeliveryDate           string  `json:"delivery_date"`
	SuccessDeliveryDate    string  `json:"success_delivery_date"`
	PartnerTransactionCode string  `json:"partner_transaction_code"`
	PartnerStatus          string  `json:"partner_status"`
	OrgId                  int     `json:"org_id"`
	UpdatedByOrgId         int     `json:"updated_by_org_id"`
	OrgHistoryId           int     `json:"org_history_id"`
	SellerOrgHistoryId     int     `json:"seller_org_history_id"`
	BuyerOrgHistoryId      int     `json:"buyer_org_history_id"`
	CustomerHistoryId      int     `json:"customer_history_id"`
	ReasonId               int     `json:"reason_id"`
	Note                   string  `json:"note"`
	ReturnNote             string  `json:"return_note"`
	ReturnReason           string  `json:"return_reason"`
	BeforeStatus           string  `json:"before_status"`
	Status                 string  `json:"status"`
	ReturnStatus           string  `json:"return_status"`
	RefId                  string  `json:"ref_id"`
	Branch                 string  `json:"branch"`
	ReferralCode           string  `json:"referral_code"`
	OrgOrderCode           string  `json:"org_order_code"`
	CreatedAt              string  `json:"created_at"`
	CreatedBy              string  `json:"created_by"`
	UpdatedAt              string  `json:"updated_at"`
	UpdatedBy              string  `json:"updated_by"`
	DeletedAt              string  `json:"deleted_at"`
	DeletedBy              string  `json:"deleted_by"`
	Resource               string  `json:"resource"`
	IsSync                 int     `json:"is_sync"`
	SyncStatus             string  `json:"sync_status"`
	LastSyncAt             string  `json:"last_sync_at"`
	IsAutoSync             int     `json:"is_auto_sync"`
	CountFail              int     `json:"count_fail"`
	SenderName             string  `json:"sender_name"`
	SenderPhone            string  `json:"sender_phone"`
	SenderAddressId        int     `json:"sender_address_id"`
	SenderAddress          string  `json:"sender_address"`
	SenderProvinceId       int     `json:"sender_province_id"`
	SenderDistrictId       int     `json:"sender_district_id"`
	SenderWardId           int     `json:"sender_ward_id"`
	RecipientName          string  `json:"recipient_name"`
	RecipientPhone         string  `json:"recipient_phone"`
	RecipientAddressId     int     `json:"recipient_address_id"`
	RecipientAddress       string  `json:"recipient_address"`
	RecipientProvinceId    int     `json:"recipient_province_id"`
	RecipientDistrictId    int     `json:"recipient_district_id"`
	RecipientWardId        int     `json:"recipient_ward_id"`
	CartId                 string  `json:"cart_id"`
	AgentBranch            string  `json:"agent_branch"`
	Customer               string  `json:"customer"`
	EcoCustomerId          string  `json:"eco_customer_id"`
	CustomerNote           string  `json:"customer_note"`
	ConsumerChannel        string  `json:"consumer_channel"`
	EfundTransactionId     int     `json:"efund_transaction_id"`
	UpdatingEfundStatus    string  `json:"updating_efund_status"`
	IsReported             int     `json:"is_reported"`
	MessageReport          string  `json:"message_report"`
	Latitude               float32 `json:"latitude"`
	Longitude              float32 `json:"longitude"`
	ReportDate             string  `json:"report_date"`
	CanceledBy             string  `json:"canceled_by"`
	CanceledAt             string  `json:"canceled_at"`
	CreatorType            string  `json:"creator_type"`
	ThirdPartyCode         string  `json:"third_party_code"`
	ThirdPartyOrderId      string  `json:"third_party_order_id"`
	ThirdPartyOrderCode    string  `json:"third_party_order_code"`
	ParentOrderId          string  `json:"parent_order_id"`
	SalesmanOrderId        string  `json:"salesman_order_id"`
	SalesmanOrderCode      string  `json:"salesman_order_code"`
	GaoStockinOrderId      string  `json:"gao_stockin_order_id"`
	GaoStockinOrderCode    string  `json:"gao_stockin_order_code"`
	KidoSyncStatus         string  `json:"kido_sync_status"`
	KidoLastSync           string  `json:"kido_last_sync"`
	BusinessTypeId         int     `json:"business_type_id"`
	BusinessTypeName       string  `json:"business_type_name"`
	NumOfPrint             int     `json:"num_of_print"`
	IsLoyaltyPoint         int     `json:"is_loyalty_point"`
	LoyaltyReqId           string  `json:"loyalty_req_id"`
	LoyaltyPoint           int     `json:"loyalty_point"`
	LoyaltyDiscountAmount  int     `json:"loyalty_discount_amount"`
	PaymentChannelId       int     `json:"payment_channel_id"`
	LoyaltyTransidRef      string  `json:"loyalty_transid_ref"`
	LoyaltyAccumulatePoint int     `json:"loyalty_accumulate_point"`
	SendNotiDeliveryCount  int     `json:"send_noti_delivery_count"`
}
